const catalog = [
  ["Ubuntu 26.04 LTS", "resolute", "ubuntu:26.04", "Stable"],
  ["Ubuntu 24.04 LTS", "noble", "ubuntu:24.04", "Recommended"],
  ["Ubuntu 22.04 LTS", "jammy", "ubuntu:22.04", "Stable"],
  ["Debian 12", "bookworm", "images:debian/12", "Stable"],
  ["Debian 13", "trixie", "images:debian/13", "Stable"],
  ["Debian 11", "bullseye", "images:debian/11", "Stable"],
  ["Debian 14 (testing)", "forky", "images:debian/14", "Advanced"],
  ["Debian Sid", "sid", "images:debian/sid", "Advanced"],
  ["Alpine 3.24", "3.24", "images:alpine/3.24", "Advanced"],
  ["Alpine 3.23", "3.23", "images:alpine/3.23", "Stable"],
  ["Alpine 3.22", "3.22", "images:alpine/3.22", "Stable"],
  ["Alpine 3.21", "3.21", "images:alpine/3.21", "Stable"],
  ["Alpine Edge", "edge", "images:alpine/edge", "Advanced"],
  ["Rocky Linux 9", "9", "images:rockylinux/9", "Stable"],
  ["Rocky Linux 8", "8", "images:rockylinux/8", "Stable"],
  ["AlmaLinux 9", "9", "images:almalinux/9", "Stable"],
  ["AlmaLinux 8", "8", "images:almalinux/8", "Stable"],
  ["CentOS Stream 10", "10-Stream", "images:centos/10-Stream", "Stable"],
  ["CentOS Stream 9", "9-Stream", "images:centos/9-Stream", "Stable"],
  ["Fedora 44", "44", "images:fedora/44", "Advanced"],
  ["Fedora 43", "43", "images:fedora/43", "Stable"],
  ["Amazon Linux 2023", "2023", "images:amazonlinux/2023", "Stable"],
  ["Arch Linux", "current", "images:archlinux", "Advanced"],
  ["Gentoo Linux (systemd)", "current", "images:gentoo/systemd", "Advanced"],
  ["Gentoo Linux (OpenRC)", "current", "images:gentoo/openrc", "Advanced"],
  ["Oracle Linux 9", "9", "images:oracle/9", "Advanced"],
  ["Oracle Linux 8", "8", "images:oracle/8", "Stable"],
  ["openEuler 24.03", "24.03", "images:openeuler/24.03", "Stable"],
  ["openSUSE 16.0", "16.0", "images:opensuse/16.0", "Stable"],
  ["openSUSE Tumbleweed", "tumbleweed", "images:opensuse/tumbleweed", "Advanced"],
  ["Devuan Excalibur", "excalibur", "images:devuan/excalibur", "Stable"],
  ["Devuan Daedalus", "daedalus", "images:devuan/daedalus", "Stable"],
  ["Linux Mint 21.3", "virginia", "images:mint/21.3", "Stable"],
  ["ALT Linux p11", "p11", "images:alt/p11", "Advanced"],
  ["ALT Linux Sisyphus", "Sisyphus", "images:alt/Sisyphus", "Advanced"],
  ["Slackware Current", "current", "images:slackware", "Advanced"],
  ["Void Linux", "current", "images:voidlinux", "Advanced"],
  ["OpenWrt 24.10", "24.10", "images:openwrt/24.10", "Advanced"],
  ["OpenWrt 25.12", "25.12", "images:openwrt/25.12", "Stable"],
  ["OpenWrt Snapshot", "snapshot", "images:openwrt/snapshot", "Advanced"],
  ["Kali Linux", "current", "images:kali", "Advanced"],
];

export const DEFAULT_DISTRIBUTION = "Ubuntu 24.04 LTS";
export const DISTRIBUTIONS = catalog.map(([name, release, alias, support]) => ({ name, release, alias, support }));

export function distributionByName(name) {
  return DISTRIBUTIONS.find((distribution) => distribution.name === name) || null;
}
